default['yum']['main']['obsoletes'] = false
default[:mongodb][:package_version] = '2.4.9-mongodb_1'
default['mongodb']['cluster_name'] = 'vzdev'
default['mongodb']['is_shard'] = true
# shard1 configuration
default['mongodb']['instance_name'] = 'shard1'
default['mongodb']['config']['shardsvr'] = 'true'
default['mongodb']['config']['port'] = 27017
default['mongodb']['config']['logpath'] = '/data/shard1/log/shard1.log'
default['mongodb']['config']['logappend'] = 'true'
default['mongodb']['config']['pidfilepath'] = '/data/shard1/db/shard1.pid'
default['mongodb']['config']['dbpath'] = '/data/shard1/db'
default['mongodb']['config']['fork'] = 'true'
